version: '3'
services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8090:8000'
  ecp:
    build: ./web
    command: python3 ECP_PDF.py
    volumes:
      - .:/web_django
