# Generated by Django 3.1.7 on 2021-03-09 19:33

import PDFEditor.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathESP', models.FileField(upload_to='pathESP/%Y/%m/%d/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Файл ЭЦП')),
            ],
        ),
        migrations.CreateModel(
            name='Wotermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAdd', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dataUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('pathOld', models.FileField(upload_to='pathOld/%Y/%m/%d/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Исходный файл')),
                ('pathESP', models.FileField(upload_to='pathESP/%Y/%m/%d/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Готовый файл')),
                ('status', models.CharField(max_length=25, verbose_name='Статус')),
                ('pathNew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFEditor.ecp', verbose_name='Файл ЭЦП')),
                ('user_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
