# Generated by Django 3.1.7 on 2021-04-10 14:51

import PDFEditor.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PDFEditor', '0003_auto_20210404_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecp',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ecp',
            name='user_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecp',
            name='pathESP',
            field=models.FileField(upload_to='pathESP/%Y/%m/%d/%H/%M/%S/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Файл ЭЦП'),
        ),
        migrations.AlterField(
            model_name='wotermark',
            name='pathESP',
            field=models.FileField(blank=True, upload_to='pathESP/%Y/%m/%d/%H/%M/%S/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Готовый файл'),
        ),
        migrations.AlterField(
            model_name='wotermark',
            name='pathOld',
            field=models.FileField(upload_to='pathOld/%Y/%m/%d/%H/%M/%S/', validators=[PDFEditor.validators.validate_file_extension], verbose_name='Исходный файл'),
        ),
    ]
