# Generated by Django 3.1.7 on 2021-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFEditor', '0004_auto_20210410_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecp',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Наименование'),
        ),
    ]
